server:
  servlet:
    context-path: /api/person
app:
  file_name: data.zip
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true